name: 'tag-release-commit'
description: 'Adds a release tag to the head commit if its commit message matches the pattern of a release commit.'
inputs:
  release-commit-message-pattern:
    description: 'Pattern to identify a release commit. The pattern is interpreted as regular expression. This action expects the release version to be captured in the first capturing group.'
    required: false
    default: 'release: v(\d+\S+)'
  expected-version:
    description: 'Allows specifying the version expected for the release commit. If the specified version and the version of the release commit do not match, then this action sets its status to failed, resulting in concurrent actions being cancelled and future actions being skipped. Has no effect if not a release commit.'
    required: false
outputs:
  is-release-commit:
    description: 'True if identified the head commit as release commit, or false otherwise.'
  version:
    description: 'The release version, or empty if not identified the head commit as release commit.'
runs:
  using: 'node12'
  main: 'dist/index.js'
